In [1]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

list1
list2

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"

In [2]:
list12 <- c(list1, list2)

print(list12)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "water"

[[5]]
[1] "juice"

[[6]]
[1] "lemonade"



In [3]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

print(unlist(list1))
print(unlist(list2))

print(mode(list1))
print(mode(unlist(list1)))

[1] 1 2 3
[1] "water"    "juice"    "lemonade"
[1] "list"
[1] "numeric"


In [4]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

append(list1, 100)
append(list2, "coffee")

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 100

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"

[[4]]
[1] "coffee"

In [5]:
list1 <- list(1, 2, 3)

append(list1, 100, after = 2)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 100

[[4]]
[1] 3

In [6]:
list1 <- list(1, 2, 3)

append(list1, 100, after = 2)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 100

[[4]]
[1] 3

In [7]:
list1 <- list(1, 2, 3)

append(list1, 100, after = 2)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 100

[[4]]
[1] 3

In [8]:
list1 <- list(1, 2, 3)

list1[-2]

[[1]]
[1] 1

[[2]]
[1] 3

In [9]:
list1 <- list(1, 2, 3, 4, 5, 6)

list1[2:4]
list1[c(1, 3, 5)]

[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 4

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 5

In [10]:
x <- 1:10

print(x)

 [1]  1  2  3  4  5  6  7  8  9 10


In [11]:
x[x > 5]

[1]  6  7  8  9 10

In [12]:
x[x %% 2 == 0]

[1]  2  4  6  8 10

In [13]:
x[x %% 2 == 1]

[1] 1 3 5 7 9

In [14]:
x <- 1:10

x[5] <- NA

print(x)

 [1]  1  2  3  4 NA  6  7  8  9 10


In [15]:
y <- x[!is.na(x)]

print(y)

[1]  1  2  3  4  6  7  8  9 10


In [16]:
mean(x)
mean(y)

[1] NA

[1] 5.555556

In [17]:
x <- 1:10

x[-(1:5)]

[1]  6  7  8  9 10

In [18]:
x[6:10]

[1]  6  7  8  9 10

In [19]:
x <- c(water = 1, juice = 2, lemonade = 3)

print(x)

   water    juice lemonade 
       1        2        3 


In [20]:
names(x)

[1] "water"    "juice"    "lemonade"

In [21]:
x["juice"]

juice 
    2

In [22]:
x <- 1:10

print(x[])

 [1]  1  2  3  4  5  6  7  8  9 10


In [23]:
gender <- factor(c("Male", "Female", "Female", "Male", "Female"))

print(gender)

[1] Male   Female Female Male   Female
Levels: Female Male


In [24]:
levels(gender)

[1] "Female" "Male"

In [25]:
y <- c(1, 4, 3, 5, 4, 2, 4)

possible.dieface <- c(1, 2, 3, 4, 5, 6)

labels.dieface <- c(
  "one", "two", "three",
  "four", "five", "six"
)

In [26]:
facy <- factor(
  y,
  levels = possible.dieface,
  labels = labels.dieface
)

print(facy)

[1] one   four  three five  four  two   four 
Levels: one two three four five six


In [27]:
levels(facy)

[1] "one"   "two"   "three" "four"  "five"  "six"

In [28]:
x <- c(3, 4, 5, 6, 1, 2, 3, 3, 4, 4, 5, 6)

y <- as.factor(x)

print(y)
levels(y)

 [1] 3 4 5 6 1 2 3 3 4 4 5 6
Levels: 1 2 3 4 5 6


[1] "1" "2" "3" "4" "5" "6"

In [29]:
class(9)

class("9")

class(print)

[1] "numeric"

[1] "character"

[1] "function"

In [30]:
x <- matrix(nrow = 2, ncol = 2, data = 1:4)

print(x)

class(x)

     [,1] [,2]
[1,]    1    3
[2,]    2    4


[1] "matrix" "array"

In [31]:
brands <- c("A", "A", "B", "B", "B", "B", "C")

brands_fac <- factor(brands)

print(brands_fac)

[1] A A B B B B C
Levels: A B C


In [32]:
unclass(brands_fac)

[1] 1 1 2 2 2 2 3
attr(,"levels")
[1] "A" "B" "C"

In [33]:
colours <- c("blue", "green", "red")

colours[unclass(brands_fac)]

[1] "blue"  "blue"  "green" "green" "green" "green" "red"

In [34]:
income <- ordered(
  c("high", "high", "low", "medium", "medium"),
  levels = c("low", "medium", "high")
)

print(income)

[1] high   high   low    medium medium
Levels: low < medium < high


In [35]:
unclass(income)

[1] 3 3 1 2 2
attr(,"levels")
[1] "low"    "medium" "high"

In [36]:
print(sqrt(2))

[1] 1.414214


In [37]:
print(sqrt(2), digits = 5)

print(sqrt(2), digits = 10)

[1] 1.4142
[1] 1.414213562


In [38]:
print("apple")

print(c("apple", "banana"))

print(c("apple", "banana", 6, 10))

[1] "apple"
[1] "apple"  "banana"
[1] "apple"  "banana" "6"      "10"    


In [39]:
format(0.5, digits = 10, nsmall = 15)

[1] "0.500000000000000"

In [40]:
x <- c("A", "BB", "CCC", "DDDD")

format(x, width = 7, justify = "left")

format(x, width = 7, justify = "right")

format(x, width = 7, justify = "centre")

format(x, width = 7, justify = "none")

[1] "A      " "BB     " "CCC    " "DDDD   "

[1] "      A" "     BB" "    CCC" "   DDDD"

[1] "   A   " "  BB   " "  CCC  " " DDDD  "

[1] "A"    "BB"   "CCC"  "DDDD"

In [41]:
print(sqrt(2))

[1] 1.414214


In [42]:
print(sqrt(2), digits = 5)

print(sqrt(2), digits = 10)

[1] 1.4142
[1] 1.414213562


In [43]:
print("apple")

[1] "apple"


In [44]:
print(c("apple", "banana"))

[1] "apple"  "banana"


In [45]:
print(c("apple", "banana", 6, 10))

[1] "apple"  "banana" "6"      "10"    


In [46]:
x <- 123.456789

format(x)

[1] "123.4568"

In [47]:
format(x, digits = 5)

[1] "123.46"

In [48]:
format(0.5, digits = 10, nsmall = 15)

[1] "0.500000000000000"

In [49]:
x <- c("A", "BB", "CCC", "DDDD")

format(x, width = 7, justify = "centre")

[1] "   A   " "  BB   " "  CCC  " " DDDD  "

In [50]:
x <- c("A", "BB", "CCC", "DDDD")

format(x, width = 7, justify = "left")

[1] "A      " "BB     " "CCC    " "DDDD   "

In [51]:
x <- c("A", "BB", "CCC", "DDDD")

format(x, width = 7, justify = "left")

[1] "A      " "BB     " "CCC    " "DDDD   "

In [52]:
format(x, width = 7, justify = "right")

[1] "      A" "     BB" "    CCC" "   DDDD"

In [53]:
format(x, width = 7, justify = "none")

[1] "A"    "BB"   "CCC"  "DDDD"

In [54]:
x <- matrix(
  nrow = 3,
  ncol = 2,
  data = 1:6,
  byrow = TRUE
)

print(x)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


In [55]:
format(1234567, big.mark = ",")

[1] "1,234,567"

In [56]:
format(12345678, big.mark = ",")

[1] "12,345,678"

In [57]:
format(123456789, big.mark = ",")

[1] "123,456,789"

In [58]:
format(123456789, big.mark = " ")

[1] "123 456 789"

In [59]:
# Vector
x <- 1:10
print(x)

# Vector indexing
print(x[x > 5])
print(x[x %% 2 == 0])

# List
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

# Merge lists
list12 <- c(list1, list2)
print(list12)

# Convert list to vector
print(unlist(list1))

# Factor
gender <- factor(c("Male", "Female", "Female", "Male"))
print(gender)
print(levels(gender))

# Named vector
drinks <- c(water = 1, juice = 2, lemonade = 3)
print(drinks["juice"])

# String formatting
print("Hello R")

# Format number
print(format(0.5, digits = 10, nsmall = 5))

# Large number formatting
print(format(123456789, big.mark = ","))

# Matrix
m <- matrix(1:6, nrow = 3, ncol = 2, byrow = TRUE)
print(m)

 [1]  1  2  3  4  5  6  7  8  9 10
[1]  6  7  8  9 10
[1]  2  4  6  8 10
[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "water"

[[5]]
[1] "juice"

[[6]]
[1] "lemonade"

[1] 1 2 3
[1] Male   Female Female Male  
Levels: Female Male
[1] "Female" "Male"  
juice 
    2 
[1] "Hello R"
[1] "0.50000"
[1] "123,456,789"
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
